### ISSUE TITLE
Error on compiling RecordDecoderFocused.cpp

### ISSUE THREAD

**Issue by tom5079** [MinhasKamal/StupidKeyLogger#5]
I got an error message "RecordDecoderFocused.cpp:101:9: error: 'remember' was not declared in this scope" and whole bunch of warning message that says "ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]" when I compiled it

**Comment by MinhasKamal** [comment]
I have updated the code. Thanks YOU a lot for referring the issue.

Sorry for late response :)
